baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "rexablog"
theme = "KeepIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-142539359-1"
disqusShortname = "rexablog"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

[params]
    since = 2019
    author = "rexagod"
    subtitle = "Pranshu Srivastava"
    cdn_url = ""
    home_mode = ""

    # google_verification = ""
    # bing_verification = ""
    # yandex_verification = ""
    # pinterest_verification = ""
    # baidu_verification = ""
    
    # avatar = "/images/me/avatar.jpg"
    socialShare = true
    
    description = "rexagod's blog"
    keywords = "rexagod, gsoc, google, summer, code, summer of code, public, lab, publiclab, public lab"

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.gravatar]
    email = "rexagod@gmail.com"

[params.social]
    GitHub = "rexagod"
    Linkedin = "rexagod"
    Email   = "rexagod@gmail.com"

[params.share]
Twitter = true
Linkedin = true
Facebook = true

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "rexagod"

  [params.publisher]
    name = "rexagod"

    [params.publisher.logo]
      url = ""
      width = 127
      height = 40

  [params.logo]
    url = ""
    width = 127
    height = 40

  [params.image]
    url = ""
    width = 800
    height = 600

# [params.gitalk]           
# owner = ""              
# repo = ""               
# clientId = ""           
# clientSecret = ""   

# [params.valine]
#   enable = false
#   appId = 'your appId'
#   appKey = 'your appKey'
#   notify = false  # mail notifier, https://github.com/xCss/Valine/wiki
#   verify = false # verification code
#   avatar = 'mm'
#   placeholder = 'Say something!'
#   visitor = true
